# Generated by Django 4.2.6 on 2023-11-03 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fec_nac', models.DateField()),
                ('domicilio', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.provincia')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'agendas',
                'db_table': 'agenda',
            },
        ),
    ]
