# Generated by Django 4.2.6 on 2023-11-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='imagen',
            field=models.ImageField(null=True, upload_to='agenda'),
        ),
    ]
